// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heforaanyuamqipcrsws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZm9yYWFueXVhbXFpcGNyc3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzY1MzMsImV4cCI6MjA1NDg1MjUzM30.cd3UvVXPr4G3iJKO9u5R68UQNrpS2JfYfT3aMHFX9UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);